export const data = {
  Zürich: {
    London: {
      duration_train: '09:05',
      duration_plane: '03:09',
      duration_winner: 'plane',
      prize_train: '284',
      prize_plane: '75',
      prize_winner: 'plane',
      co2_train: '19.6',
      co2_plane: '138.5',
      co2_winner: 'train',
      changes_train: '2',
      changes_plane: '0',
      changes_winner: 'plane',
    },
    Berlin: {
      duration_train: '08:28',
      duration_plane: '02:55',
      duration_winner: 'plane',
      prize_train: '33',
      prize_plane: '116',
      prize_winner: 'train',
      co2_train: '30.7',
      co2_plane: '120.8',
      co2_winner: 'train',
      changes_train: '1',
      changes_plane: '0',
      changes_winner: 'plane',
    },
    'Berlin (Nachtzug)': {
      duration_train: '11:39',
      duration_plane: '02:55',
      duration_winner: 'plane',
      prize_train: '154',
      prize_plane: '116',
      prize_winner: 'plane',
      co2_train: '30.7',
      co2_plane: '120.8',
      co2_winner: 'train',
      changes_train: '0',
      changes_plane: '0',
    },
    Amsterdam: {
      duration_train: '07:59',
      duration_plane: '03:07',
      duration_winner: 'plane',
      prize_train: '77',
      prize_plane: '181',
      prize_winner: 'train',
      co2_train: '26.8',
      co2_plane: '127.1',
      co2_winner: 'train',
      changes_train: '1',
      changes_plane: '0',
      changes_winner: 'plane',
    },
    Wien: {
      duration_train: '07:50',
      duration_plane: '02:38',
      duration_winner: 'plane',
      prize_train: '104',
      prize_plane: '208',
      prize_winner: 'train',
      co2_train: '12.4',
      co2_plane: '126.4',
      co2_winner: 'train',
      changes_train: '0',
      changes_plane: '0',
    },
    'Wien (Nachtzug)': {
      duration_plane: '02:38',
      duration_train: '10:15',
      duration_winner: 'plane',
      prize_plane: '208',
      prize_train: '142',
      prize_winner: 'train',
      co2_train: '12.4',
      co2_plane: '126.4',
      co2_winner: 'train',
      changes_train: '0',
      changes_plane: '0',
    },
    Paris: {
      duration_train: '04:04',
      duration_plane: '02:54',
      duration_winner: 'plane',
      prize_train: '169',
      prize_plane: '93',
      prize_winner: 'plane',
      co2_train: '6.4',
      co2_plane: '113.6',
      co2_winner: 'train',
      changes_train: '0',
      changes_plane: '0',
    },
    Barcelona: {
      duration_train: '11:01',
      duration_plane: '03:12',
      duration_winner: 'plane',
      prize_train: '195',
      prize_plane: '208',
      prize_winner: 'train',
      co2_train: '11.5',
      co2_plane: '142.1',
      co2_winner: 'train',
      changes_train: '2',
      changes_plane: '0',
      changes_winner: 'plane',
    },
    Hamburg: {
      duration_train: '07:37',
      duration_plane: '03:08',
      duration_winner: 'plane',
      prize_train: '80',
      prize_plane: '132',
      prize_winner: 'train',
      co2_train: '24.8',
      co2_plane: '126.6',
      co2_winner: 'train',
      changes_train: '0',
      changes_plane: '0',
    },
    'Hamburg (Nachtzug)': {
      duration_plane: '03:08',
      duration_train: '12:25',
      duration_winner: 'plane',
      prize_plane: '132',
      prize_train: '154',
      prize_winner: 'plane',
      co2_train: '24.8',
      co2_plane: '126.6',
      co2_winner: 'train',
      changes_train: '0',
      changes_plane: '0',
      trees_train: 1,
      trees_plane: 11,
    },
    Prag: {
      duration_train: '10:18',
      duration_plane: '02:43',
      duration_winner: 'plane',
      prize_train: '42',
      prize_plane: '327',
      prize_winner: 'train',
      co2_train: '64.4',
      co2_plane: '121.8',
      co2_winner: 'train',
      changes_train: '3',
      changes_plane: '0',
      changes_winner: 'plane',
    },
    'Prag (Nachtzug)': {
      duration_plane: '02:43',
      duration_train: '13:16',
      duration_winner: 'plane',
      prize_plane: '327',
      prize_train: '116',
      prize_winner: 'train',
      co2_train: '64.4',
      co2_plane: '121.8',
      co2_winner: 'train',
      changes_train: '0',
      changes_plane: '0',
    },
    Budapest: {
      duration_train: '10:39',
      duration_plane: '03:11',
      duration_winner: 'plane',
      prize_train: '155',
      prize_plane: '344',
      prize_winner: 'train',
      co2_train: '21.1',
      co2_plane: '145.1',
      co2_winner: 'train',
      changes_train: '0',
      changes_plane: '0',
    },
    'Budapest (Nachtzug)': {
      duration_plane: '03:11',
      duration_train: '12:47',
      duration_winner: 'plane',
      prize_plane: '344',
      prize_train: '56',
      prize_winner: 'train',
      co2_train: '21.1',
      co2_plane: '145.1',
      co2_winner: 'train',
      changes_train: '0',
      changes_plane: '0',
    },
    Rom: {
      duration_train: '07:16',
      duration_plane: '03:05',
      duration_winner: 'plane',
      prize_train: '165',
      prize_plane: '84',
      prize_winner: 'plane',
      co2_train: '28.5',
      co2_plane: '127.8',
      co2_winner: 'train',
      changes_train: '1',
      changes_plane: '0',
      changes_winner: 'plane',
    },
    Venedig: {
      duration_train: '06:09',
      duration_plane: '02:33',
      duration_winner: 'plane',
      prize_train: '94',
      prize_plane: '332',
      prize_winner: 'train',
      co2_train: '15.5',
      co2_plane: '132.5',
      co2_winner: 'train',
      changes_train: '0',
      changes_plane: '0',
      trees_train: 1,
      trees_plane: 11,
    },
    Brüssel: {
      duration_train: '06:13',
      duration_plane: '02:33',
      duration_winner: 'plane',
      prize_train: '242',
      prize_plane: '248',
      prize_winner: 'train',
      co2_train: '9.7',
      co2_plane: '114.7',
      co2_winner: 'train',
      changes_train: '3',
      changes_plane: '0',
      changes_winner: 'plane',
    },
    Kopenhagen: {
      duration_train: '13:34',
      duration_plane: '03:08',
      duration_winner: 'plane',
      prize_train: '89',
      prize_plane: '195',
      prize_winner: 'train',
      co2_train: '48.1',
      co2_plane: '157.1',
      co2_winner: 'train',
      changes_train: '1',
      changes_plane: '0',
      changes_winner: 'plane',
    },
  },
  Basel: {
    London: {
      duration_train: '08:09',
      duration_plane: '03:04',
      duration_winner: 'plane',
      prize_train: '252',
      prize_plane: '52',
      prize_winner: 'plane',
      co2_train: '18.1',
      co2_plane: '127.1',
      co2_winner: 'train',
      changes_train: '3',
      changes_plane: '0',
      changes_winner: 'plane',
    },
    Berlin: {
      duration_train: '07:14',
      duration_plane: '02:40',
      duration_winner: 'plane',
      prize_train: '69',
      prize_plane: '154',
      prize_winner: 'train',
      co2_train: '28.8',
      co2_plane: '124.9',
      co2_winner: 'train',
      changes_train: '0',
      changes_plane: '0',
    },
    'Berlin (Nachtzug)': {
      duration_train: '10:34',
      duration_plane: '02:40',
      duration_winner: 'plane',
      prize_train: '93',
      prize_plane: '154',
      prize_winner: 'train',
      co2_train: '28.8',
      co2_plane: '124.9',
      co2_winner: 'train',
      changes_train: '0',
      changes_plane: '0',
    },
    Amsterdam: {
      duration_train: '07:15',
      duration_plane: '02:48',
      duration_winner: 'plane',
      prize_train: '88',
      prize_plane: '114',
      co2_train: '25.5',
      co2_plane: '118.3',
      co2_winner: 'train',
      changes_train: '1',
      changes_plane: '0',
      changes_winner: 'plane',
    },
    Wien: {
      duration_train: '08:57',
      duration_plane: '02:59',
      duration_winner: 'plane',
      prize_train: '128',
      prize_plane: '98',
      prize_winner: 'plane',
      co2_train: '12.3',
      co2_plane: '123.8',
      co2_winner: 'train',
      changes_train: '1',
      changes_plane: '0',
      changes_winner: 'plane',
    },
    Paris: {
      duration_train: '03:04',
      duration_plane: '02:34',
      duration_winner: 'plane',
      prize_train: '163',
      prize_plane: '101',
      prize_winner: 'plane',
      co2_train: '3.5',
      co2_plane: '98',
      co2_winner: 'train',
      changes_train: '0',
      changes_plane: '0',
    },
    Barcelona: {
      duration_train: '09:32',
      duration_plane: '03:15',
      duration_winner: 'plane',
      prize_train: '195',
      prize_plane: '102',
      prize_winner: 'plane',
      co2_train: '10.9',
      co2_plane: '148.3',
      co2_winner: 'train',
      changes_train: '2',
      changes_plane: '0',
      changes_winner: 'plane',
    },
    Hamburg: {
      duration_train: '06:30',
      duration_plane: '03:07',
      duration_winner: 'plane',
      prize_train: '55',
      prize_plane: '92',
      prize_winner: 'train',
      co2_train: '23.5',
      co2_plane: '126.6',
      co2_winner: 'train',
      changes_train: '0',
      changes_plane: '0',
    },
    'Hamburg (Nachtzug)': {
      duration_plane: '03:07',
      duration_train: '11:11',
      duration_winner: 'plane',
      prize_plane: '92',
      prize_train: '154',
      prize_winner: 'plane',
      co2_train: '23.5',
      co2_plane: '126.6',
      co2_winner: 'train',
      changes_train: '0',
      changes_plane: '0',
    },
    Prag: {
      duration_train: '10:08',
      duration_plane: '02:50',
      duration_winner: 'plane',
      prize_train: '42',
      prize_plane: '70',
      prize_winner: 'train',
      co2_train: '38.7',
      co2_plane: '120.2',
      co2_winner: 'train',
      changes_train: '3',
      changes_plane: '0',
      changes_winner: 'plane',
    },
    Budapest: {
      duration_train: '11:46',
      duration_plane: '03:27',
      duration_winner: 'plane',
      prize_train: '177',
      prize_plane: '111',
      prize_winner: 'plane',
      co2_train: '20.8',
      co2_plane: '145.6',
      co2_winner: 'train',
      changes_train: '1',
      changes_plane: '0',
      changes_winner: 'plane',
    },
    Rom: {
      duration_train: '08:07',
      duration_plane: '02:54',
      duration_winner: 'plane',
      prize_train: '197',
      prize_plane: '134',
      prize_winner: 'plane',
      co2_train: '28.8',
      co2_plane: '138.0',
      co2_winner: 'train',
      changes_train: '2',
      changes_plane: '0',
      changes_winner: 'plane',
    },
    Venedig: {
      duration_train: '07:09',
      duration_plane: '05:03',
      duration_winner: 'plane',
      prize_train: '126',
      prize_plane: '191',
      prize_winner: 'train',
      co2_train: '16.9',
      co2_plane: '214.6',
      co2_winner: 'train',
      changes_train: '1',
      changes_plane: '1',
    },
    Brüssel: {
      duration_train: '05:13',
      duration_plane: '02:25',
      duration_winner: 'plane',
      prize_train: '237',
      prize_plane: '218',
      prize_winner: 'plane',
      co2_train: '7.1',
      co2_plane: '103.1',
      co2_winner: 'train',
      changes_train: '2',
      changes_plane: '0',
      changes_winner: 'plane',
    },
    Kopenhagen: {
      duration_train: '12:27',
      duration_plane: '03:11',
      duration_winner: 'plane',
      prize_train: '66',
      prize_plane: '174',
      prize_winner: 'train',
      co2_train: '46.8',
      co2_plane: '158.7',
      co2_winner: 'train',
      changes_train: '1',
      changes_plane: '0',
      changes_winner: 'plane',
    },
  },
}

export const customData = {
  Mailand: {
    duration_train: '08:06',
    duration_plane: '03:33',
    duration_winner: 'plane',
    prize_train: '150',
    prize_plane: '20',
    prize_winner: 'plane',
    co2_train: '15.4',
    co2_plane: '134.1',
    co2_winner: 'train',
    changes_train: '2',
    changes_plane: '0',
    changes_winner: 'plane',
  },
  Madrid: {
    duration_train: '12:31',
    duration_plane: '02:35',
    duration_winner: 'plane',
    prize_train: '68',
    prize_plane: '20',
    prize_winner: 'plane',
    co2_train: '22.3',
    co2_plane: '149',
    co2_winner: 'train',
    changes_train: '2',
    changes_plane: '0',
    changes_winner: 'plane',
  },
  Budapest: {
    duration_train: '72:00',
    duration_plane: '03:20',
    duration_winner: 'plane',
    prize_train: '160',
    prize_plane: '64',
    prize_winner: 'plane',
    co2_train: '144.2',
    co2_plane: '230',
    co2_winner: 'train',
    changes_train: '10',
    changes_plane: '0',
    changes_winner: 'plane',
  },
  London: {
    duration_train: '09:05',
    duration_plane: '03:09',
    duration_winner: 'plane',
    prize_train: '284',
    prize_plane: '75',
    prize_winner: 'plane',
    co2_train: '19.6',
    co2_plane: '138.5',
    co2_winner: 'train',
    changes_train: '2',
    changes_plane: '0',
    changes_winner: 'plane',
  },
}
